---
title: "adspj4"
output: html_document
---

```{r}
ratings <- read.csv("~/Desktop/fall2019-project4-sec2-grp7/data/ml-latest-small/ratings.csv", stringsAsFactors=FALSE)
load("/Users/ss/Desktop/fall2019-project4-sec2-grp7/output/mat_fac.RData")
```


#5 users 10 movies
p = result$p[1:10,1:4]
q = result$q[1:10,1:5]
#t(q) %*% p

t(p) %*% q



yij =beta1 * pi^t * qj + beta2 * pi^t * q(NN of item j)
```{r}
p = result$p
q = result$q
s = matrix(NA,dim(q)[2],dim(q)[2])
for(i in 1:dim(q)[2]){
  for(j in 1:dim(q)[2]){
   s[i,j] =  (t(q[,i])%*%q[,j])/(sqrt(t(q[,i]) %*% q[,i])*sqrt(t(q[,j]) %*% q[,j]))
  }
}
#colnames(s) = ratings$movieId[1:dim(q)[2]]
#rownames(s) = ratings$movieId[1:dim(q)[2]]
s
save(s,file = "../output/s.RData")
```


```{r}
load("../output/s.Rdata")
#3NN
K = 4
#1st movie similarity
knn = matrix(NA,dim(ratings)[1],3)

index = c()

for(i in 1:100836){
  index[i] = which(colnames(q) == ratings$movieId[i])
}


for(i in 1:100836){
  knn[i,] = order(s[index[i],],decreasing = T)[2:K]
}


ratings  = cbind(ratings,knn)

```

```{r}

est_rate_orig = matrix(NA,100836,1)
for (i in 1:100836){
  est_rate_orig[i,] = t(p[,ratings$userId[i]]) %*% q[,as.numeric(index[i])]
}

est_rate = matrix(NA,100836,(K-1))
for (i in 1:100836){
  est_rate[i,] = t(p[,ratings$userId[i]]) %*% q[,as.numeric(ratings[,c(5:7)][i,])]
}

reg = cbind(ratings$rating,est_rate_orig,est_rate)
reg = as.data.frame(reg)

knn = lm(reg$V1~reg$V2)
mean((predict(knn)-reg$V1)^2)
```
